In [7]:
import os
import datetime
import pandas as pd

In [23]:
file_dir = r"C:\Users\nikol\OneDrive\Escritorio\VMG30_05_08_2023_12_09_04.csv"

In [24]:
def get_file_creation_time(file_dir):
    info_archivo = os.stat(file_dir)
    timestamp_creacion = info_archivo.st_ctime
    fecha_hora_creacion = datetime.datetime.fromtimestamp(timestamp_creacion)

    formato_deseado = fecha_hora_creacion.strftime('%Y-%m-%d-%H:%M:%S.%f')

    return formato_deseado

creation_time = get_file_creation_time(file_dir)
creation_time = pd.to_datetime(creation_time, format='%Y-%m-%d-%H:%M:%S.%f')

def restar_segundos(row):
    segundos_a_restar = row['Seconds']
    nueva_fecha = creation_time - pd.Timedelta(seconds=segundos_a_restar)
    return nueva_fecha


df = pd.read_csv(file_dir, sep='\t')
df['Seconds'] = df['STAMP']/1000
df['Sample_Time'] = df.apply(restar_segundos, axis=1)
df

,STAMP,ROOT X,ROOT Y,ROOT Z,WRIST X,WRIST Y,WRIST Z,HAND X,HAND Y,HAND Z,...,DIST THUMB-RING,DIST THUMB-LITTLE,DIST PALM-THUMB,DIST PALM-INDEX,DIST PALM-MIDDLE,DIST PALM-RING,DIST PALM-LITTLE,Unnamed: 98,Seconds,Sample_Time
0,430,"0,0000","0,0000","0,0000","-0,3034","58,7415","-6,2373","-30,0236","137,0194","-50,4604",...,"138,71","157,69","118,28","106,69","129,42","103,82","99,26",NaN,0.43,2023-08-05 15:15:40.868312
1,870,"0,0000","0,0000","0,0000","-1,6083","58,4674","-8,1224","-30,2277","137,1914","-52,2047",...,"139,33","158,00","118,36","106,81","129,46","103,87","99,18",NaN,0.87,2023-08-05 15:15:40.428312
2,1300,"0,0000","0,0000","0,0000","6,2898","58,2117","-7,1750","-9,1819","140,7269","-50,6811",...,"139,66","157,88","118,09","107,25","129,72","103,97","99,03",NaN,1.30,2023-08-05 15:15:39.998312
3,1730,"0,0000","0,0000","0,0000","13,1246","56,9060","-7,4843","13,2561","140,7214","-50,8694",...,"132,42","138,97","108,15","111,49","132,32","106,86","97,02",NaN,1.73,2023-08-05 15:15:39.568312
4,2160,"0,0000","0,0000","0,0000","10,8373","57,4278","-6,8086","3,9004","136,7744","-57,3155",...,"131,48","142,14","104,99","112,87","133,22","107,40","99,19",NaN,2.16,2023-08-05 15:15:39.138312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133,57800,"0,0000","0,0000","0,0000","12,8619","53,6584","-20,9829","3,9191","139,1564","-60,5388",...,"58,68","96,81","94,74","113,95","132,68","98,51","103,85",NaN,57.80,2023-08-05 15:14:43.498312
134,58230,"0,0000","0,0000","0,0000","17,0049","57,1126","-21,2161","13,0591","149,9548","-61,7828",...,"100,45","117,96","106,10","123,30","132,41","115,57","109,16",NaN,58.23,2023-08-05 15:14:43.068312
135,58660,"0,0000","0,0000","0,0000","40,0991","135,0983","-48,0122","35,2850","356,1312","-137,8629",...,"206,03","247,67","216,29","288,47","126,56","268,94","264,86",NaN,58.66,2023-08-05 15:14:42.638312
136,59090,"0,0000","0,0000","0,0000","39,4022","134,9857","-48,8976","36,1342","355,7795","-139,4033",...,"206,08","240,02","211,74","288,05","127,44","270,87","265,68",NaN,59.09,2023-08-05 15:14:42.208312
137,59530,"0,0000","0,0000","0,0000","36,9784","136,4072","-46,8009","17,3249","357,3162","-134,9191",...,"202,15","236,50","209,66","288,35","127,44","271,08","266,06",NaN,59.53,2023-08-05 15:14:41.768312